B=32
N=8
L=1024

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=/checkpoint/ram/tianjian/wildchat10k.parquet \
    data.val_files=/checkpoint/ram/tianjian/creative_writing_data/valid.parquet \
    data.prompt_key="prompt" \
    data.train_batch_size=${B} \
    data.max_prompt_length=512 \
    data.max_response_length=${L} \
    data.filter_overlong_prompts=True \
    data.truncation='error' \
    actor_rollout_ref.model.path=/datasets/pretrained-llms/Llama-3.1-8B-Instruct \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=40000 \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=True \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.8 \
    actor_rollout_ref.rollout.n=${N} \
    actor_rollout_ref.rollout.val_kwargs.n=8 \
    actor_rollout_ref.rollout.val_kwargs.do_sample=True \
    actor_rollout_ref.rollout.temperature=1.0 \
    actor_rollout_ref.rollout.val_kwargs.temperature=1.0 \
    actor_rollout_ref.ref.log_prob_use_dynamic_bsz=True \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.use_kl_in_reward=False \
    custom_reward_function.path=/home/$USER/diverse_responses/verl/verl/utils/reward_score/diversity_rewards.py \
    custom_reward_function.name=ngram \
    reward_model.reward_manager=diversity \
    reward_model.enable=True \
    reward_model.model.input_tokenizer=/checkpoint/ram/tianjian/reward_models/Athene-RM-8B \
    reward_model.model.path=/checkpoint/ram/tianjian/reward_models/Athene-RM-8B \
    reward_model.micro_batch_size_per_gpu=16 \
    trainer.critic_warmup=0 \
    trainer.logger=['console','wandb'] \
    trainer.project_name='athene' \
    trainer.experiment_name=quality_only_b${B}_n${N}_l${L} \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=200 \
    trainer.test_freq=200 \
    trainer.default_local_dir=/checkpoint/ram/tianjian/checkpoints_athene/wildchat10k_quality_only_b${B}_n${N}_l${L}_baseline \
    trainer.validation_data_dir=/checkpoint/ram/tianjian/checkpoints_athene/wildchat10k_quality_only_b${B}_n${N}_l${L}_baseline/rollouts \
    trainer.total_epochs=10 $@ +reward_model.lambda_rule_rescale=0.0 
